nombre = input("ingresa tu nombre")
edad = input("ingresa tu edad")
numero = input("ingresa tu numero de celular")
departamento = input("ingresa el departamento")
municipio = input("ingresa el municipio")
direccionlocal = input("ingresa tu dirreccion local")
curs = input("ingresa tus cursos")
certificados = input("ingresa tus certificados")
años = input("ingresa los años de experiencia laboral")
empresa = input("ingresa nombre de la empresa")
cargo = input("ingresa el cargo que ocupaste")
informacion = tuple((nombre,edad,numero))
direccion = tuple((departamento,municipio,direccionlocal))
cursos = tuple((curs, certificados))
experiencia = tuple((años,empresa,cargo))
print(informacion,direccion,cursos,experiencia)